#!/usr/bin/env bash

link() {
  from="$HOME/.dotfiles/$1"
  to="$HOME/$2"
  echo "New symlink $to -> $from"
  rm -f $to
  ln -s $from $to
}

# Link necessary files
for file in .{bashrc,gitconfig,hgrc,tmux.conf,vimrc}; do
  link $file $file
done

link ".bashrc" ".bash_profile"

# Link Atom Editor configuration
mkdir -p $HOME/.atom
files=`ls $HOME/.dotfiles/atom`
for file in $files; do
  link atom/$file .atom/$file
done
