#!/usr/bin/env bash

git submodule init
git submodule update

link() {
  from="$HOME/.dotfiles/$1"
  to="$HOME/$2"
  echo "New symlink $to -> $from"
  rm -f $to
  ln -s $from $to
}

linkr() {
  mkdir -p $HOME/.$1
  files=`ls $HOME/.dotfiles/$1`
  for file in $files; do
    link $1/$file .$1/$file
  done
}

# Link necessary files
for file in .{bashrc,gitconfig,hgrc,tmux.conf,vimrc,vim,pypirc}; do
  link $file $file
done

link ".bashrc" ".bash_profile"

linkr atom
linkr lein
