#!/usr/bin/env bash

# Install brew
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"

# Temporarily add brew's bin directory to the path so that
# this problem will not be reported by brew doctor.
export PATH="/usr/local/bin:$PATH"
 
# Make sure brew is up to date
brew update
brew upgrade

# Check that everything is ok with the system config
brew doctor
if [[ $? -gt 0 ]]; then
	echo "Please make sure that there are no brew problems."
	exit 1
fi
 
# Install command line tools
brew install ack \
			 autoconf \
			 automake \
			 bash \
			 curl \
			 gibo \
			 git \
			 leiningen \
			 maven \
			 mercurial \
			 ncdu \
			 sbt \
			 terminal-notifier \
			 tmux \
			 tree \
			 vim \
			 wget

# Install cask so that we can install standard apps
brew tap phinze/homebrew-cask
brew install brew-cask
 
function installcask() {
  brew cask install "${@}" 2> /dev/null
}
 
installcask dropbox
installcask google-chrome
installcask google-chrome-canary
installcask firefox
installcask imagealpha
installcask imageoptim
installcask iterm2
installcask miro-video-converter
installcask sublime-text-3
installcask the-unarchiver
installcask ukelele
installcask virtualbox
installcask vlc
installcask dash
installcask caffeine
installcask wireshark
installcask sourcetree
installcask google-hangouts
installcask divvy
installcask skype
installcask keepass-x
installcask kindle
installcask spotify
installcask tunnelblick
installcask light-table
installcask libre-office
installcask iterm2
installcask inkscape
installcask heroku-toolbelt
installcask balsamiq-mockups
installcask xmind
installcask gimp
installcask gmail-notifr
installcask vagrant
installcask tor-browser
installcask steam
installcask hipchat
 
brew cleanup