#!/usr/bin/env bash

# Install brew
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
 
# Check that your path is setup correctly etc.
# TODO stop if brew detects problems
brew doctor
 
# Make sure brew is up to date
brew update
brew upgrade
 
# Install command line tools
brew install ack curl autoconf automake wget bash leiningen ncdu tmux tree gibo git mercurial vim maven terminal-notifier
 
brew tap phinze/homebrew-cask
brew install brew-cask
 
function installcask() {
  brew cask install "${@}" 2> /dev/null
}
 
installcask dropbox
installcask google-chrome
installcask google-chrome-canary
installcask firefox
installcask imagealpha
installcask imageoptim
installcask iterm2
installcask miro-video-converter
installcask sublime-text-3
installcask the-unarchiver
installcask ukelele
installcask virtualbox
installcask vlc
installcask dash
installcask caffeine
installcask wireshark
installcask sourcetree
installcask google-hangouts
installcask divvy
installcask skype
installcask keepass-x
installcask kindle
installcask spotify
installcask tunnelblick
installcask light-table
installcask libre-office
installcask iterm2
installcask inkscape
installcask heroku-toolbelt
installcask balsamiq-mockups
installcask xmind
installcask gimp
installcask gmail-notifr
installcask vagrant
installcask tor-browser
installcask steam
 
brew cleanup