#!/usr/bin/env bash

set -e

# make sure that address resolution for bripkens works
sudo sh -c 'echo "127.0.0.1    bripkens\n" >> /etc/hosts'

# ICIS+
# route lab traffic through the company gateway
sudo route -n add 172.30.0.0/24 10.10.10.4

# route dev tools traffic through the company gateway
sudo route -n add 192.168.0.0/24 10.10.10.4
