#!/usr/bin/env bash

# Install NVM
curl https://raw.github.com/creationix/nvm/master/install.sh | sh

# Download last stable Node.JS version
nvm install 0.10

# Set stable version as default version
nvm alias default 0.10
