#!/usr/bin/env bash

# Install NVM
curl https://raw.github.com/creationix/nvm/master/install.sh | sh

node_version="0.10"
# Download last stable Node.JS version
nvm install $node_version

# Set stable version as default version
nvm alias default $node_version
